# config.yml

ssh_config:
  host: "203.161.53.228"
  port: 22
  user: "root"
  private_key: "C:\\Users\\CloudDevWayne\\.ssh\\id_rsa"
  tunnels:
    - local_port: 8080
      remote_port: 9000
    - local_port: 5000
      remote_port: 7000
